/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  content: ["./src/**/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "background-black": "#2D3239",
        "background-tan": "#F3EEE1",
        "background-light-tan": "#F5F1E9",
        "background-light-teal": "#EBF3F3",
        "background-grey-0": "#F2F2F2",
        "background-white": "#FFFFFF",
        "background-bright-teal": "#008F94",
        "background-dark-teal": "#00666E",
        "background-error-alert": "#DA574B",
        "background-default-alert-fill": "#E5E5E5",
        "brand-sun": "#FAC816",
        "brand-teal": "#00818A",
        "brand-road": "#2C323A",
        "brand-warmth": "#F3EEE1",
        "brand-earth": "#F3EEE1",
        "brand-legacy-yellow": "#FFDE00",
        "brand-legacy-teal": "#009999",
        "brand-legacy-black": "#2C323A",
        "ui-black": "#2C323A",
        "ui-grey-4": "#4D4D4D",
        "ui-grey-3": "#757575",
        "ui-grey-2": "#9E9E9E",
        "ui-grey-1": "#E0E0E0",
        "ui-grey-0": "#F2F2F2",
        "ui-white": "#FFFFFF",
        "ui-success": "#1DA887",
        "ui-error": "#DA574B",
        "ui-link": "#009999",
      },
    },
  },
  plugins: [],
};